DROP TABLE IF EXISTS CARS CASCADE;

CREATE TABLE IF NOT EXISTS CARS(
	ID SERIAL PRIMARY KEY,
	PRICE INT4,
	REGION VARCHAR(244),
	KM INT4,
	YEAR INT2,
	DATE VARCHAR(15),
	LINK VARCHAR(244),
	TITLE VARCHAR(244),
	DESCRIPTION VARCHAR(244),
	MODEL VARCHAR(80),
	POWER INT2,
	COLOR VARCHAR(20),
	DOORS INT2,
	STEERING VARCHAR(10),
	OPTIONAL VARCHAR(244),
	CEP INT2,
	CITY VARCHAR(244));